# This file created by conda-build 24.7.1
# ------------------------------------------------

package:
  name: mamba
  version: 1.5.9
source:
  sha256: 59d7dd68a8e4cf70448b54f9f2ec9a9de8b1d46c8cc4d80790b0ed4a7b5e5169
  url: https://github.com/mamba-org/mamba/archive/refs/tags/2024.08.31.tar.gz
build:
  entry_points:
    - mamba = mamba.mamba:main
  number: 0
  string: py312h14bc7db_0
requirements:
  build:
    - bzip2 1.0.8 hfdf4475_7
    - ca-certificates 2024.8.30 h8857fd0_0
    - cctools_osx-64 986 h6e61e4f_3
    - cctools_osx-arm64 986 hffacd06_3
    - clang 18.1.8 default_h179603d_3
    - clang-18 18.1.8 default_h0c94c6a_3
    - clang_impl_osx-arm64 18.1.8 hadf8e89_19
    - clang_osx-arm64 18.1.8 h40be2b1_19
    - clangxx 18.1.8 default_h179603d_3
    - compiler-rt 18.1.8 h734a56e_0
    - compiler-rt_osx-64 18.1.8 h7312ed1_0
    - cross-python_osx-arm64 3.12 42_cpython
    - crossenv 1.4.0 pyhd8ed1ab_0
    - gettext 0.22.5 hdfe23c8_3
    - gettext-tools 0.22.5 hdfe23c8_3
    - icu 75.1 h120a0e1_0
    - ld64_osx-64 711 h93b84b6_3
    - ld64_osx-arm64 711 hf597abb_3
    - libasprintf 0.22.5 hdfe23c8_3
    - libasprintf-devel 0.22.5 hdfe23c8_3
    - libclang-cpp18.1 18.1.8 default_h0c94c6a_3
    - libcxx 18.1.8 hd876a4e_6
    - libcxx-devel 18.1.8 h7c275be_6
    - libexpat 2.6.2 h73e2aa4_0
    - libffi 3.4.2 h0d85af4_5
    - libgettextpo 0.22.5 hdfe23c8_3
    - libgettextpo-devel 0.22.5 hdfe23c8_3
    - libiconv 1.17 hd75f5a5_2
    - libintl 0.22.5 hdfe23c8_3
    - libintl-devel 0.22.5 hdfe23c8_3
    - libllvm18 18.1.8 h9ce406d_2
    - libsqlite 3.46.0 h1b8f9f3_0
    - libxml2 2.12.7 heaf3512_4
    - libzlib 1.3.1 h87427d6_1
    - llvm-tools 18.1.8 h9ce406d_2
    - llvm-tools-18 18.1.8 h9ce406d_2
    - lz4-c 1.9.4 hf0c8a7f_0
    - ncurses 6.5 hf036a51_1
    - openssl 3.3.1 hd23fc13_3
    - popt 1.16 h7b079dc_2002
    - python 3.12.5 h37a9e06_0_cpython
    - readline 8.2 h9e318b2_1
    - rsync 3.3.0 h5aaac6a_0
    - sed 4.7 h3efe00b_1000
    - sigtool 0.1.3 h88f4db0_0
    - tapi 1100.0.11 h9ce4665_0
    - tk 8.6.13 h1abcd95_1
    - tzdata 2024a h8827d51_1
    - xxhash 0.8.2 h4140336_0
    - xz 5.2.6 h775f41a_0
    - zstd 1.5.6 h915ae27_0
  host:
    - bzip2 1.0.8 h99b78c6_7
    - ca-certificates 2024.8.30 hf0a4a13_0
    - libexpat 2.6.2 hebf3989_0
    - libffi 3.4.2 h3422bc3_5
    - libmambapy 1.5.9 py312h1ed1908_0
    - libsqlite 3.46.0 hfb93653_0
    - libzlib 1.3.1 hfb2fe0b_1
    - ncurses 6.5 h7bae524_1
    - openssl 3.3.1 h8359307_3
    - pip 24.2 pyh8b19718_1
    - python 3.12.5 h30c5eda_0_cpython
    - readline 8.2 h92ec313_1
    - setuptools 72.2.0 pyhd8ed1ab_0
    - tk 8.6.13 h5083fa2_1
    - tzdata 2024a h8827d51_1
    - wheel 0.44.0 pyhd8ed1ab_0
    - xz 5.2.6 h57fd34a_0
  run:
    - conda >=24,<25
    - libmambapy 1.5.9 py312h1ed1908_0
    - openssl >=3.3.1,<4.0a0
    - python >=3.12,<3.13.0a0
    - python >=3.12,<3.13.0a0 *_cpython
    - python_abi 3.12.* *_cp312
test:
  commands:
    - mamba --help
    - mamba create -n test_py2 python=2.7 --dry-run
    - mamba clean --all --dry-run
    - mamba repoquery whoneeds conda
    - python -c "import mamba._version; assert mamba._version.__version__ == '1.5.9'"
    - test -f ${PREFIX}/condabin/mamba
  imports:
    - mamba
  requires:
    - pip
about:
  description: '


    [![Build Status](https://github.com/mamba-org/mamba/workflows/CI/badge.svg)](https://github.com/mamba-org/mamba/actions)

    [![Join the Gitter Chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/mamba-org/Lobby?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

    [![docs](https://readthedocs.org/projects/mamba/badge/?version=latest&style=flat)](https://mamba.readthedocs.io/en/latest)


    `mamba` is a reimplementation of the conda package manager in C++.


    - parallel downloading of repository data and package files using multi-threading

    - libsolv for much faster dependency solving, a state of the art library used
    in the RPM package manager of Red Hat, Fedora and OpenSUSE

    - core parts of `mamba` are implemented in C++ for maximum efficiency


    At the same time, `mamba` utilizes the same command line parser, package installation
    and deinstallation code and transaction verification routines as `conda` to stay
    as compatible as possible.


    Mamba is part of a bigger ecosystem to make scientific packaging more sustainable.
    You can read our [announcement blog post](https://medium.com/@QuantStack/open-software-packaging-for-science-61cecee7fc23).

    The ecosystem also consists of `quetz`, an open source `conda` package server
    and `boa`, a fast `conda` package builder.




    Please refer to the [`mamba` and `micromamba` installation guide](https://mamba.readthedocs.io/en/latest/installation.html)
    in the documentation.




    `mamba` and `micromamba` come with features on top of stock `conda`.




    To efficiently query repositories and query package dependencies you can use `mamba
    repoquery` or `micromamba repoquery`.

    See the [repoquery documentation](https://mamba.readthedocs.io/en/latest/user_guide/mamba.html#repoquery)
    for details.




    `micromamba` can be used to install lock files generated by [conda-lock](https://conda-incubator.github.io/conda-lock/)
    without having to install `conda-lock`. Simply invoke e.g. `micromamba create
    -n my-env -f conda-lock.yml` with an environment lockfile named `*-lock.yml` or
    `*-lock.yaml`.

    '
  dev_url: https://github.com/mamba-org/mamba
  home: https://github.com/mamba-org/mamba
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A fast drop-in alternative to conda, using libsolv for dependency resolution
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240830.4.1
  recipe-maintainers:
    - AntoinePrv
    - JohanMabille
    - SylvainCorlay
    - adriendelsalle
    - ericmjl
    - wolfv
  remote_url: https://github.com/conda-forge/mamba-feedstock
  sha: 007d0b11444c409601b83577afb70f96a94731d5
